name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: kenichirokimura/md2pdf:latest
      volumes:
        - my_docker_volume:/docs
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Md2pdf
        run: /usr/bin/md2pdf.sh
      - name: upload assets
        uses: actions/upload-artifact@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: docs
          path: docs.tgz
