name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: kenichirokimura/md2pdf:latest
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1
      - name: Md2pdf
        run: |
          echo ${{ steps.changed-files.outputs.all_modified_files }}
          /usr/bin/md2pdf.sh ${{ steps.changed-files.outputs.all_modified_files }}
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          release_id: ${{ steps.latest_release_info.outputs.id }}
          asset_path: ./docs.tgz
          asset_name: docs-$$.tgz
          asset_content_type: application/x-gzip
