name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: kenichirokimura/md2pdf:latest
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10.1
      - name: Check diff files  
        run: echo ${{ steps.changed-files.outputs.all_modified_files }}
      - name: Md2pdf
        run: /usr/bin/md2pdf.sh
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Remove asset
        uses: flcdrg/remove-release-asset-action@v1
        id: remove
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.latest_release_info.outputs.id }}
          asset_name: docs.tgz
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: ./docs.tgz
          asset_name: docs.tgz
          asset_content_type: application/x-gzip
